services:
  app:
    build:
      context: ../.
      dockerfile: ./Cascade.Example/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__CascadeDb=Data Source=db;Initial Catalog=Cascade;User ID=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      DB_NAME: "Cascade"
    ports:
      - "1433:1433"