// <auto-generated />
using System;
using Flagsmith.EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flagsmith.EntityFramework.SqlServer.Migrations
{
    [DbContext(typeof(FlagsmithDbContext))]
    [Migration("20250201032115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flagsmith.EntityFramework.Models.FeatureFlagEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("Flagsmith.EntityFramework.Models.TenantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Flagsmith.EntityFramework.Models.TenantOverrideEntity", b =>
                {
                    b.Property<string>("FeatureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FeatureId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantOverrides", (string)null);
                });

            modelBuilder.Entity("Flagsmith.EntityFramework.Models.TenantOverrideEntity", b =>
                {
                    b.HasOne("Flagsmith.EntityFramework.Models.FeatureFlagEntity", "Feature")
                        .WithMany("TenantOverrides")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flagsmith.EntityFramework.Models.TenantEntity", "Tenant")
                        .WithMany("FeatureOverrides")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Flagsmith.EntityFramework.Models.FeatureFlagEntity", b =>
                {
                    b.Navigation("TenantOverrides");
                });

            modelBuilder.Entity("Flagsmith.EntityFramework.Models.TenantEntity", b =>
                {
                    b.Navigation("FeatureOverrides");
                });
#pragma warning restore 612, 618
        }
    }
}
