// <auto-generated />
using System;
using Cascade.EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cascade.EntityFramework.SqlServer.Migrations
{
    [DbContext(typeof(CascadeDbContext))]
    partial class CascadeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cascade.EntityFramework.Models.FeatureFlagEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("Cascade.EntityFramework.Models.TenantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Cascade.EntityFramework.Models.TenantOverrideEntity", b =>
                {
                    b.Property<string>("FeatureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("TenantEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FeatureId", "TenantId");

                    b.HasIndex("TenantEntityId");

                    b.ToTable("TenantOverrides", (string)null);
                });

            modelBuilder.Entity("Cascade.EntityFramework.Models.TenantOverrideEntity", b =>
                {
                    b.HasOne("Cascade.EntityFramework.Models.FeatureFlagEntity", "Feature")
                        .WithMany("TenantOverrides")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cascade.EntityFramework.Models.TenantEntity", null)
                        .WithMany("FeatureOverrides")
                        .HasForeignKey("TenantEntityId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Cascade.EntityFramework.Models.FeatureFlagEntity", b =>
                {
                    b.Navigation("TenantOverrides");
                });

            modelBuilder.Entity("Cascade.EntityFramework.Models.TenantEntity", b =>
                {
                    b.Navigation("FeatureOverrides");
                });
#pragma warning restore 612, 618
        }
    }
}
